remote_theme: tedivm/jekyll-theme-portfolio

title: Francesco Colangelo
author: Francesco Colangelo
email: tua-email@esempio.com
description: >
  Ingegnere meccanico specializzato in progettazione CAD e analisi strutturale.

homepage: https://francescocolangelo99.github.io
linkedin_username: il-tuo-username-linkedin
github_username: francescocolangelo99

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
